/** Commandes unifiées de l’app → clés API par plateforme */

export const ROKU_KEYS: Record<string, string> = {
  power: 'Power',
  vol_up: 'VolumeUp',
  vol_down: 'VolumeDown',
  mute: 'VolumeMute',
  ch_up: 'ChannelUp',
  ch_down: 'ChannelDown',
  up: 'Up',
  down: 'Down',
  left: 'Left',
  right: 'Right',
  ok: 'Select',
  back: 'Back',
  home: 'Home',
  menu: 'Info',
  source: 'InputTuner',
  play: 'Play',
  pause: 'Play',
  stop: 'Back',
  num_0: 'Lit_0',
  num_1: 'Lit_1',
  num_2: 'Lit_2',
  num_3: 'Lit_3',
  num_4: 'Lit_4',
  num_5: 'Lit_5',
  num_6: 'Lit_6',
  num_7: 'Lit_7',
  num_8: 'Lit_8',
  num_9: 'Lit_9',
  rewind: 'Rev',
  fast_forward: 'Fwd',
  search: 'Search',
  info: 'Info',
  instant_replay: 'InstantReplay',
};

/** Codes IRCC Sony Bravia (base64) — jeux courants */
export const SONY_IRCC: Record<string, string> = {
  power: 'AAAAAQAAAAEAAAAVAw==',
  vol_up: 'AAAAAQAAAAEAAAASAw==',
  vol_down: 'AAAAAQAAAAEAAAATAw==',
  mute: 'AAAAAQAAAAEAAAAUAw==',
  ch_up: 'AAAAAQAAAAEAAAAQAw==',
  ch_down: 'AAAAAQAAAAEAAAARAw==',
  up: 'AAAAAQAAAAEAAAB0Aw==',
  down: 'AAAAAQAAAAEAAAB1Aw==',
  left: 'AAAAAQAAAAEAAAB2Aw==',
  right: 'AAAAAQAAAAEAAAB3Aw==',
  ok: 'AAAAAQAAAAEAAABlAw==',
  back: 'AAAAAgAAAJcAAAAjAw==',
  home: 'AAAAAQAAAAEAAABgAw==',
  menu: 'AAAAAgAAAJcAAAAjAw==',
  source: 'AAAAAQAAAAEAAAAnAw==',
  num_0: 'AAAAAQAAAAEAAAAJAw==',
  num_1: 'AAAAAQAAAAEAAAAMAw==',
  num_2: 'AAAAAQAAAAEAAAANAw==',
  num_3: 'AAAAAQAAAAEAAAAOAw==',
  num_4: 'AAAAAQAAAAEAAAAPAw==',
  num_5: 'AAAAAQAAAAEAAAAQAw==',
  num_6: 'AAAAAQAAAAEAAAARAw==',
  num_7: 'AAAAAQAAAAEAAAASAw==',
  num_8: 'AAAAAQAAAAEAAAATAw==',
  num_9: 'AAAAAQAAAAEAAAAUAw==',
  play: 'AAAAAgAAAJcAAAAaAw==',
  pause: 'AAAAAgAAAJcAAAAZAw==',
  stop: 'AAAAAgAAAJcAAAAYAw==',
};

export const PHILIPS_KEYS: Record<string, string> = {
  power: 'KEY_POWER',
  vol_up: 'KEY_VOLUME_UP',
  vol_down: 'KEY_VOLUME_DOWN',
  mute: 'KEY_MUTE',
  ch_up: 'KEY_CHANNEL_UP',
  ch_down: 'KEY_CHANNEL_DOWN',
  up: 'KEY_CURSOR_UP',
  down: 'KEY_CURSOR_DOWN',
  left: 'KEY_CURSOR_LEFT',
  right: 'KEY_CURSOR_RIGHT',
  ok: 'KEY_OK',
  back: 'KEY_BACK',
  home: 'KEY_HOME',
  menu: 'KEY_OPTIONS',
  source: 'KEY_SOURCE',
  num_0: 'KEY_0',
  num_1: 'KEY_1',
  num_2: 'KEY_2',
  num_3: 'KEY_3',
  num_4: 'KEY_4',
  num_5: 'KEY_5',
  num_6: 'KEY_6',
  num_7: 'KEY_7',
  num_8: 'KEY_8',
  num_9: 'KEY_9',
};

export const LG_KEYS: Record<string, string> = {
  power: 'POWER',
  vol_up: 'VOLUMEUP',
  vol_down: 'VOLUMEDOWN',
  mute: 'MUTE',
  ch_up: 'CHANNELUP',
  ch_down: 'CHANNELDOWN',
  up: 'UP',
  down: 'DOWN',
  left: 'LEFT',
  right: 'RIGHT',
  ok: 'ENTER',
  back: 'BACK',
  home: 'HOME',
  menu: 'MENU',
  source: 'INPUT',
  num_0: '0',
  num_1: '1',
  num_2: '2',
  num_3: '3',
  num_4: '4',
  num_5: '5',
  num_6: '6',
  num_7: '7',
  num_8: '8',
  num_9: '9',
};

export const SAMSUNG_KEYS: Record<string, string> = {
  power: 'KEY_POWER',
  vol_up: 'KEY_VOLUP',
  vol_down: 'KEY_VOLDOWN',
  mute: 'KEY_MUTE',
  ch_up: 'KEY_CHUP',
  ch_down: 'KEY_CHDOWN',
  up: 'KEY_UP',
  down: 'KEY_DOWN',
  left: 'KEY_LEFT',
  right: 'KEY_RIGHT',
  ok: 'KEY_ENTER',
  back: 'KEY_RETURN',
  home: 'KEY_HOME',
  menu: 'KEY_MENU',
  source: 'KEY_SOURCE',
  play: 'KEY_PLAY',
  pause: 'KEY_PAUSE',
  stop: 'KEY_STOP',
  num_0: 'KEY_0',
  num_1: 'KEY_1',
  num_2: 'KEY_2',
  num_3: 'KEY_3',
  num_4: 'KEY_4',
  num_5: 'KEY_5',
  num_6: 'KEY_6',
  num_7: 'KEY_7',
  num_8: 'KEY_8',
  num_9: 'KEY_9',
};

/** Commandes lancement d’apps (Roku ECP /launch) */
export const STREAMING_APP_COMMANDS = [
  'netflix',
  'youtube',
  'prime',
  'disney',
  'spotify',
  'hulu',
  'plex',
] as const;

export type StreamingAppCommand = (typeof STREAMING_APP_COMMANDS)[number];

export function isStreamingAppCommand(command: string): command is StreamingAppCommand {
  return (STREAMING_APP_COMMANDS as readonly string[]).includes(command);
}
